/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadeiaDeValorRouteImport } from './routes/cadeia-de-valor'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'
import { Route as ProcessosCodigoRouteImport } from './routes/processos.$codigo'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as WorkflowCodigoRouteImport } from './routes/workflow.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadeiaDeValorRoute = CadeiaDeValorRouteImport.update({
  id: '/cadeia-de-valor',
  path: '/cadeia-de-valor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosCodigoRoute = ProcessosCodigoRouteImport.update({
  id: '/processos/$codigo',
  path: '/processos/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowCodigoRoute = WorkflowCodigoRouteImport.update({
  id: '/workflow/$codigo',
  path: '/workflow/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadeia-de-valor': typeof CadeiaDeValorRoute
  '/processos/$codigo': typeof ProcessosCodigoRoute
  '/workflow/$codigo': typeof WorkflowCodigoRoute
  '/processos/': typeof ProcessosIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadeia-de-valor': typeof CadeiaDeValorRoute
  '/processos/$codigo': typeof ProcessosCodigoRoute
  '/workflow/$codigo': typeof WorkflowCodigoRoute
  '/processos': typeof ProcessosIndexRoute
  '/workflow': typeof WorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadeia-de-valor': typeof CadeiaDeValorRoute
  '/processos/$codigo': typeof ProcessosCodigoRoute
  '/workflow/$codigo': typeof WorkflowCodigoRoute
  '/processos/': typeof ProcessosIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadeia-de-valor'
    | '/processos/$codigo'
    | '/workflow/$codigo'
    | '/processos/'
    | '/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadeia-de-valor'
    | '/processos/$codigo'
    | '/workflow/$codigo'
    | '/processos'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/cadeia-de-valor'
    | '/processos/$codigo'
    | '/workflow/$codigo'
    | '/processos/'
    | '/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadeiaDeValorRoute: typeof CadeiaDeValorRoute
  ProcessosCodigoRoute: typeof ProcessosCodigoRoute
  WorkflowCodigoRoute: typeof WorkflowCodigoRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadeia-de-valor': {
      id: '/cadeia-de-valor'
      path: '/cadeia-de-valor'
      fullPath: '/cadeia-de-valor'
      preLoaderRoute: typeof CadeiaDeValorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/$codigo': {
      id: '/processos/$codigo'
      path: '/processos/$codigo'
      fullPath: '/processos/$codigo'
      preLoaderRoute: typeof ProcessosCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/workflow'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$codigo': {
      id: '/workflow/$codigo'
      path: '/workflow/$codigo'
      fullPath: '/workflow/$codigo'
      preLoaderRoute: typeof WorkflowCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadeiaDeValorRoute: CadeiaDeValorRoute,
  ProcessosCodigoRoute: ProcessosCodigoRoute,
  WorkflowCodigoRoute: WorkflowCodigoRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
